name: ayaha_reason
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  sqflite: ^2.4.2
  share_plus: ^11.0.0
  google_fonts: ^6.2.1
  path: ^1.9.1
  flutter_bloc: ^9.1.1
  http: ^1.4.0
  audioplayers: ^6.4.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icons/images.jpg'

flutter:

  uses-material-design: true

  assets:
  - assets/fonts/Tajawal/
  - assets/audio/quruan.m4a
  - assets/image/

  fonts:
  - family: Tajawal
    fonts:
    - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
      weight: 300
    - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
      weight: 400
    - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
      weight: 700
